# Generated by Django 4.0.6 on 2022-07-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(choices=[('Berry', 'Aguav Berry'), ('Berry ', 'Apicot Berry'), ('Berry ', 'Aspear Berry'), ('Berry ', ' Babiri Berry'), ('Berry ', 'Charti Berry'), ('Berry ', 'Chesto Berry'), ('Berry 7', 'Chilan Berry'), ('Berry 8', 'Chople Berry'), ('Berry 9', 'Colbur Berry'), ('Berry 10', 'Custap Berry'), ('Berry 11', 'Enigma Berry'), ('Berry 12', 'Ganlon Berry'), ('Berry 13', 'Golden Golden Nanab Berry'), ('Berry 14', 'Golden Golden Pinap Berry'), ('Berry 15', 'Golden Razz Berry'), ('Berry 16', 'Hondew Berry'), ('Berry 17', 'Iapapa Berry'), ('Berry 18', 'Iapapa Berry'), ('Berry 19', 'Jaboca Berry'), ('Berry 20', 'Lansat Berry'), ('Berry 21', 'Liechi Berry'), ('Berry 22', 'Maranga Berry'), ('Berry 23', 'Pamtre Berry'), ('Berry 24', 'Payapa Berry'), ('Berry 25', 'Kelpsy Berry')], default='Berry', max_length=50),
        ),
    ]
