# Generated by Django 4.0.6 on 2022-07-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_items_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(choices=[('Berry 1', 'Aguav Berry'), ('Berry 2', 'Apicot Berry'), ('Berry 3', 'Aspear Berry'), ('Berry 4', ' Babiri Berry'), ('Berry 5', 'Charti Berry'), ('Battle 6', 'XAttack'), ('Battle 7', 'Reset Urge'), ('Battle 8', 'Sassy Mint'), ('Battle 9', 'Relaxed Mint'), ('Battle 10', 'Guard Spec.'), ('Battle 11', 'Brave Mint'), ('Hold 12', 'Black Belt'), ('Hold 13', 'Assualt Vest'), ('Hold 14', 'Air Ballon'), ('Hold 15', 'Absolite'), ('Machine 16', 'HM04'), ('Machine 17', 'HM03'), ('Machine 18', 'HM02'), ('Machine 19', 'HM01'), ('Machine 20', 'Lansat Berry'), ('Medicine 21', 'Clever Wing'), ('Medicine 22', 'Calcium'), ('Medicine 23', 'Burn Heal'), ('Medicine 24', 'Awakening'), ('Medicine 25', 'Antidote'), ('Berry 19', 'Jaboca Berry'), ('Berry 20', 'Lansat Berry'), ('Berry 21', 'Liechi Berry'), ('Berry 22', 'Maranga Berry'), ('Berry 23', 'Pamtre Berry'), ('Berry 24', 'Payapa Berry'), ('Berry 25', 'Kelpsy Berry')], default='Berry 1', max_length=50),
        ),
    ]
