# Generated by Django 4.0.6 on 2022-07-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_pokemon_moves_remove_pokemon_weakness'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
