# Generated by Django 4.0.6 on 2022-07-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_items_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Weakness 1', 'Normal'), ('Weakness 2', 'Fire'), ('Weakness 3', 'Water'), ('Weakness 4', ' Electric'), ('Weakness 5', 'Grass'), ('Weakness 6', 'Ice'), ('Weakness 7', 'Fighting'), ('Weakness 8', 'Poison'), ('Weakness 9', 'Ground'), ('Weakness 10', 'Flying'), ('Weakness 11', 'Psychic'), ('Weakness 12', 'Bug'), ('Weakness 13', 'Rock'), ('Weakness 14', 'Ghost'), ('Weakness 15', 'Dragon'), ('Weakness 16', 'Dark'), ('Weakness 17', 'Steel'), ('Weakness 18', 'Fairy')], default='Weakness 1', max_length=20)),
            ],
        ),
    ]
