# Generated by Django 4.0.6 on 2022-07-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_weakness'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='weakness',
            field=models.ManyToManyField(to='main_app.weakness'),
        ),
    ]
